// Generated by scripts/build-sprites.mjs from public/assets/pocket-machines/manifest.json. Do not edit.

export const ROBOTS = ["tidy","blaze","drift","hoarder"] as const;
export type SpriteRobot = (typeof ROBOTS)[number];

export const STATES = ["idle","move","hop","talk","happy","scared","guilty","thinking","signature"] as const;
export type SpriteState = (typeof STATES)[number];

export type SheetSize = "map" | "portrait";

/** Frames per sheet, laid out left to right. */
export const FRAMES = 4;

/** Timing per state, the same for every robot. */
export const ANIMATIONS: Record<SpriteState, { fps: number; loop: boolean }> = {
  "idle": {
    "fps": 2,
    "loop": true
  },
  "move": {
    "fps": 8,
    "loop": true
  },
  "hop": {
    "fps": 5,
    "loop": false
  },
  "talk": {
    "fps": 6,
    "loop": true
  },
  "happy": {
    "fps": 5,
    "loop": false
  },
  "scared": {
    "fps": 8,
    "loop": true
  },
  "guilty": {
    "fps": 5,
    "loop": false
  },
  "thinking": {
    "fps": 5,
    "loop": true
  },
  "signature": {
    "fps": 5,
    "loop": false
  }
};

/** The crop applied to each source frame, in source pixels (a source frame is 512x512). */
export const CROP = {"x":80,"y":128,"width":384,"height":344};

/** Ground anchor inside a cropped frame, in source pixels. Feet (or wheels, or the pod's float line) sit here. */
export const ANCHOR = { x: 176, y: 336 };

/** Height of the resting artwork in source pixels. */
export const ART_HEIGHT = 300;

/** Output frame sizes per sheet size, in image pixels. */
export const SHEET_SIZES: Record<SheetSize, { scale: number; frameWidth: number; frameHeight: number }> = {
  "map": {
    "scale": 0.45,
    "frameWidth": 173,
    "frameHeight": 155
  },
  "portrait": {
    "scale": 0.55,
    "frameWidth": 211,
    "frameHeight": 189
  }
};

export const sheetUrl = (size: SheetSize, robot: SpriteRobot, state: SpriteState) =>
  `/assets/pocket-machines/web/${size}/${robot}-${state}.webp`;

export const portraitUrl = (robot: SpriteRobot) => `/assets/pocket-machines/web/portraits/${robot}.webp`;
