// Edge cases found while building the first engine wave: previous-branch shortcuts, path forms of
// checkout, reset and rm, merge corner cases, push refspec forms and bad revisions.

import { commitFile, del, fails, git, stops, write, type Scenario } from "../scenario";

const P = "player";
const base = commitFile(P, "a.txt", "1\n2\n3\n4\n5\n6\n7\n8\n9\n", "Base");

export const edgeCases: Scenario[] = [
  {
    name: "switch - and checkout -",
    steps: [
      ...base,
      git(P, "switch -c f"),
      git(P, "switch -"),
      git(P, "checkout -"),
      git(P, "checkout -"),
      git(P, "switch --detach HEAD"),
      git(P, "switch -"),
    ],
  },
  {
    name: "checkout file without dashes and restore --source",
    steps: [
      ...base,
      ...commitFile(P, "b.txt", "b\n", "B"),
      write(P, "a.txt", "x\n"),
      git(P, "checkout a.txt"),
      git(P, "restore --source HEAD~1 b.txt"),
      git(P, "checkout HEAD~1 -- a.txt"),
      git(P, "status"),
    ],
  },
  {
    name: "rm variants",
    steps: [
      ...base,
      ...commitFile(P, "b.txt", "b\n", "B"),
      write(P, "b.txt", "bb\n"),
      fails(git(P, "rm b.txt")),
      git(P, "rm --cached b.txt"),
      write(P, "n.txt", "n\n"),
      git(P, "add n.txt"),
      fails(git(P, "rm n.txt")),
      git(P, "rm -f n.txt"),
      git(P, "rm a.txt"),
      git(P, "commit -m Rm"),
    ],
  },
  {
    name: "reset paths",
    steps: [
      ...base,
      write(P, "a.txt", "z\n"),
      write(P, "c.txt", "c\n"),
      git(P, "add ."),
      git(P, "reset a.txt"),
      git(P, "reset -- c.txt"),
      fails(git(P, "reset nope.txt")),
      git(P, "reset HEAD a.txt"),
    ],
  },
  {
    name: "add add conflict",
    steps: [
      ...base,
      git(P, "switch -c f"),
      ...commitFile(P, "n.txt", "one\ntwo\n", "F"),
      git(P, "switch main"),
      ...commitFile(P, "n.txt", "one\nthree\n", "M"),
      stops(git(P, "merge f")),
      git(P, "add n.txt"),
      git(P, "commit -m Merged"),
    ],
  },
  {
    name: "merge non-adjacent edits and adjacent edits",
    steps: [
      ...base,
      git(P, "switch -c f"),
      ...commitFile(P, "a.txt", "1\nF\n3\n4\n5\n6\n7\nF\n9\n", "F"),
      git(P, "switch main"),
      ...commitFile(P, "a.txt", "1\n2\n3\n4\nM\n6\n7\n8\nM\n", "M"),
      stops(git(P, "merge f -m Mg")),
    ],
  },
  {
    name: "merge with dirty files",
    steps: [
      ...base,
      ...commitFile(P, "u.txt", "u\n", "U"),
      git(P, "switch -c f HEAD~1"),
      ...commitFile(P, "a.txt", "1\n2\nF\n4\n5\n6\n7\n8\n9\n", "F"),
      git(P, "switch main"),
      ...commitFile(P, "c.txt", "c\n", "C"),
      write(P, "u.txt", "dirty\n"),
      git(P, "merge f -m Mg"),
      write(P, "a.txt", "dirty\n"),
      git(P, "merge f -m Mg2"),
      git(P, "status"),
    ],
  },
  {
    name: "criss-cross merge",
    steps: [
      ...base,
      git(P, "branch f"),
      ...commitFile(P, "m.txt", "m\n", "M1"),
      git(P, "switch f"),
      ...commitFile(P, "f.txt", "f\n", "F1"),
      git(P, "merge main -m X1"),
      git(P, "switch main"),
      git(P, "merge f~1 -m X2"),
      ...commitFile(P, "a.txt", "1\n2\n3\n4\nM\n6\n7\n8\n9\n", "M2"),
      git(P, "switch f"),
      ...commitFile(P, "a.txt", "F\n2\n3\n4\n5\n6\n7\n8\n9\n", "F2"),
      git(P, "merge main -m Final"),
    ],
  },
  {
    name: "pull ff-only and fetch prune",
    steps: [
      ...base,
      git(P, "push -u origin main"),
      git(P, "push origin main:gone"),
      git(P, "worktree add /crew/blaze"),
      ...commitFile("blaze", "z.txt", "z\n", "Z"),
      git("blaze", "push origin blaze:main"),
      git("blaze", "push origin :gone"),
      ...commitFile(P, "y.txt", "y\n", "Y"),
      fails(git(P, "pull --ff-only")),
      git(P, "fetch --prune"),
      git(P, "pull"),
      git(P, "push"),
    ],
  },
  {
    name: "dwim switch to remote branch",
    steps: [
      ...base,
      git(P, "push origin main:feat"),
      git(P, "fetch"),
      git(P, "switch feat"),
      git(P, "branch -m feat feat2"),
      fails(git(P, "switch -c t origin/main")),
      fails(git(P, "branch -d feat2")),
      fails(git(P, "branch -D feat2")),
    ],
  },
  {
    name: "unborn reset and branch ops",
    steps: [
      write(P, "a.txt", "a\n"),
      git(P, "add a.txt"),
      git(P, "reset"),
      git(P, "add a.txt"),
      git(P, "switch -c other"),
      fails(git(P, "branch x")),
      git(P, "commit -m First"),
      git(P, "branch -m other main2"),
    ],
  },
  {
    name: "merge into branch adds into",
    steps: [
      ...base,
      git(P, "switch -c dev"),
      ...commitFile(P, "d.txt", "d\n", "D"),
      git(P, "switch -c t main"),
      ...commitFile(P, "t.txt", "t\n", "T"),
      git(P, "switch dev"),
      git(P, "merge t"),
      git(P, "merge --no-ff main"),
    ],
  },
  {
    name: "detached commit amend and reflog",
    steps: [
      ...base,
      ...commitFile(P, "b.txt", "b\n", "B"),
      git(P, "checkout HEAD~1"),
      ...commitFile(P, "c.txt", "c\n", "C"),
      git(P, "commit --amend -m C2"),
      git(P, "switch main"),
      git(P, "branch rescue HEAD@{2}"),
      git(P, "reset --hard HEAD@{3}"),
    ],
  },
  {
    name: "add dir and glob",
    steps: [
      ...base,
      write(P, "src/x.ts", "x\n"),
      write(P, "src/y.ts", "y\n"),
      write(P, "z.md", "z\n"),
      git(P, "add src"),
      git(P, "commit -m Src"),
      del(P, "src/x.ts"),
      git(P, "add src"),
      git(P, "rm -r src"),
      git(P, "commit -m Gone"),
    ],
  },
  {
    name: "modify delete other way",
    steps: [
      ...base,
      git(P, "switch -c f"),
      git(P, "rm a.txt"),
      git(P, "commit -m Del"),
      git(P, "switch main"),
      ...commitFile(P, "a.txt", "changed\n", "Chg"),
      stops(git(P, "merge f")),
      git(P, "rm a.txt"),
      git(P, "commit -m Resolved"),
    ],
  },
  {
    name: "commit -a during conflict, merge --continue",
    steps: [
      ...base,
      git(P, "switch -c f"),
      ...commitFile(P, "a.txt", "F\n", "F"),
      git(P, "switch main"),
      ...commitFile(P, "a.txt", "M\n", "M"),
      stops(git(P, "merge f")),
      fails(git(P, "merge --continue")),
      write(P, "a.txt", "fixed\n"),
      git(P, "add a.txt"),
      git(P, "merge --continue"),
    ],
  },
  {
    name: "rename branch in other worktree, push delete, push -u up to date",
    steps: [
      ...base,
      git(P, "push -u origin main"),
      git(P, "worktree add /crew/blaze"),
      git(P, "branch -m blaze blaze2"),
      ...commitFile("blaze", "z.txt", "z\n", "Z"),
      git("blaze", "push -u origin blaze2"),
      git(P, "push origin --delete blaze2"),
      git(P, "push -u origin main"),
      git(P, "fetch"),
    ],
  },
  {
    name: "restore staged on conflict and reset hard during merge",
    steps: [
      ...base,
      git(P, "switch -c f"),
      ...commitFile(P, "a.txt", "F\n", "F"),
      git(P, "switch main"),
      ...commitFile(P, "a.txt", "M\n", "M"),
      stops(git(P, "merge f")),
      git(P, "restore --staged a.txt"),
      git(P, "status"),
      git(P, "reset --hard"),
      stops(git(P, "merge f")),
      fails(git(P, "checkout f")),
    ],
  },
  {
    name: "merge commit oid name and early part",
    steps: [
      ...base,
      git(P, "switch -c f"),
      ...commitFile(P, "x.txt", "x\n", "X"),
      ...commitFile(P, "y.txt", "y\n", "Y"),
      git(P, "switch main"),
      ...commitFile(P, "m.txt", "m\n", "Mm"),
      git(P, "merge f~1"),
      git(P, "reset --hard HEAD~1"),
      git(P, "merge HEAD@{2}"),
    ],
  },
  {
    name: "switch with staged changes carried and blocked",
    steps: [
      ...base,
      git(P, "switch -c f"),
      ...commitFile(P, "a.txt", "F\n", "F"),
      git(P, "switch main"),
      write(P, "n.txt", "n\n"),
      git(P, "add n.txt"),
      git(P, "switch f"),
      write(P, "a.txt", "local\n"),
      fails(git(P, "switch main")),
      git(P, "add a.txt"),
      fails(git(P, "switch main")),
      write(P, "a.txt", "F\n"),
      git(P, "add a.txt"),
      git(P, "switch main"),
    ],
  },
  {
    name: "ff merge with dirty files",
    steps: [
      ...base,
      git(P, "switch -c f"),
      ...commitFile(P, "a.txt", "F\n", "F"),
      git(P, "switch main"),
      write(P, "q.txt", "q\n"),
      git(P, "add q.txt"),
      git(P, "merge f"),
      write(P, "a.txt", "dirty\n"),
      git(P, "reset --hard HEAD~1"),
      write(P, "a.txt", "dirty\n"),
      fails(git(P, "merge f")),
    ],
  },
  {
    name: "branch from oid prefix and tilde caret",
    steps: [
      ...base,
      ...commitFile(P, "b.txt", "b\n", "B"),
      ...commitFile(P, "c.txt", "c\n", "C"),
      git(P, "branch x HEAD~2"),
      git(P, "branch y main^^"),
      git(P, "branch z HEAD^0"),
      git(P, "branch -f x y"),
      git(P, "branch w @{1}"),
      git(P, "branch v main@{0}"),
    ],
  },
  {
    name: "amend on root and empty amend",
    steps: [
      ...base,
      git(P, "commit --amend -m Base2"),
      git(P, "commit --allow-empty -m Empty"),
      fails(git(P, "commit --amend -m Empty2")),
      git(P, "commit --amend --allow-empty -m Empty3"),
    ],
  },
  {
    name: "push refspec forms and pull with args",
    steps: [
      ...base,
      git(P, "push origin HEAD"),
      git(P, "switch -c dev"),
      ...commitFile(P, "d.txt", "d\n", "D"),
      git(P, "push origin dev:main"),
      git(P, "reset --hard HEAD~1"),
      ...commitFile(P, "e.txt", "e\n", "E"),
      fails(git(P, "push origin dev:main")),
      git(P, "push origin +dev:main"),
      git(P, "pull origin main"),
      git(P, "pull --no-ff origin main"),
      fails(git(P, "push")),
    ],
  },
  {
    name: "merge blocked by untracked file",
    steps: [
      ...base,
      git(P, "switch -c f"),
      ...commitFile(P, "n.txt", "n\n", "N"),
      ...commitFile(P, "a.txt", "1\n", "A1"),
      git(P, "switch main"),
      ...commitFile(P, "o.txt", "o\n", "O"),
      write(P, "n.txt", "mine\n"),
      fails(git(P, "merge f -m Mg")),
      fails(git(P, "switch f")),
      del(P, "n.txt"),
      git(P, "merge f -m Mg"),
    ],
  },
  {
    name: "empty messages and bad revs",
    steps: [
      ...base,
      write(P, "a.txt", "q\n"),
      git(P, "add a.txt"),
      fails(git(P, ["commit", "-m", ""])),
      git(P, ["commit", "-m", "  Spaced  \n\n\nbody  "]),
      fails(git(P, "branch b nope")),
      fails(git(P, "merge nope")),
      fails(git(P, "reset --hard nope")),
      fails(git(P, "switch nope")),
      fails(git(P, "checkout nope")),
    ],
  },
  {
    name: "checkout -b with dirty tree and detached previous",
    steps: [
      ...base,
      ...commitFile(P, "b.txt", "b\n", "B"),
      write(P, "a.txt", "dirty\n"),
      git(P, "checkout -b g HEAD~1"),
      fails(git(P, "checkout HEAD~1")),
      git(P, "checkout main"),
      git(P, "checkout -"),
      git(P, "switch main"),
      git(P, "switch -"),
    ],
  },
];
