// git rebase and git pull --rebase: replaying commits, conflicts with --continue, --skip and
// --abort, commits that are already upstream, and the reflog that remembers the old commits.

import { commitFile, fails, git, stops, write, type Scenario } from "../scenario";

const P = "player";
const base = commitFile(P, "a.txt", "1\n2\n3\n", "Base");

/** main gets M (a new file), feature gets X (a new file) and F (an edit to a.txt). */
const diverged = [
  ...base,
  git(P, "switch -c feature"),
  ...commitFile(P, "x.txt", "x\n", "X"),
  ...commitFile(P, "a.txt", "1\nF\n3\n", "F"),
  git(P, "switch main"),
  ...commitFile(P, "m.txt", "m\n", "M"),
];

/** Like `diverged`, but main edits the same line of a.txt as F, so F conflicts. */
const conflicting = [
  ...base,
  git(P, "switch -c feature"),
  ...commitFile(P, "x.txt", "x\n", "X"),
  ...commitFile(P, "a.txt", "1\nF\n3\n", "F"),
  ...commitFile(P, "y.txt", "y\n", "Y"),
  git(P, "switch main"),
  ...commitFile(P, "a.txt", "1\nM\n3\n", "M"),
  git(P, "switch feature"),
];

const shared = [...base, git(P, "push -u origin main"), git(P, "worktree add /crew/blaze -b blaze origin/main")];

export const rebases: Scenario[] = [
  {
    name: "rebase replays a branch onto main",
    copiesCommits: true,
    steps: [...diverged, git(P, "switch feature"), git(P, "rebase main"), git(P, "log --oneline")],
  },
  {
    name: "rebase stops on a conflict and continues after it is resolved",
    copiesCommits: true,
    steps: [
      ...conflicting,
      stops(git(P, "rebase main")),
      git(P, "status"),
      fails(git(P, "rebase --continue")),
      fails(git(P, "rebase main")),
      write(P, "a.txt", "1\nM and F\n3\n"),
      git(P, "add a.txt"),
      git(P, "rebase --continue"),
    ],
  },
  {
    name: "rebase --skip drops the conflicting commit",
    copiesCommits: true,
    steps: [...conflicting, stops(git(P, "rebase main")), git(P, "rebase --skip"), fails(git(P, "rebase --skip"))],
  },
  {
    name: "rebase --abort goes back to the branch as it was",
    copiesCommits: true,
    steps: [...conflicting, stops(git(P, "rebase main")), git(P, "rebase --abort"), fails(git(P, "rebase --abort"))],
  },
  {
    name: "rebase a branch named on the command line, and up-to-date cases",
    copiesCommits: true,
    steps: [
      ...diverged,
      git(P, "rebase main feature"),
      git(P, "rebase main feature"),
      git(P, "rebase main"),
      git(P, "switch main"),
      git(P, "rebase main~1 feature"),
      git(P, "switch main"),
      git(P, "rebase feature"),
    ],
  },
  {
    name: "rebase --onto moves a branch that was built on another branch",
    copiesCommits: true,
    steps: [
      ...diverged,
      git(P, "switch -c topic feature"),
      ...commitFile(P, "t.txt", "t\n", "T1"),
      ...commitFile(P, "t.txt", "t2\n", "T2"),
      git(P, "rebase --onto main feature topic"),
      git(P, "rebase --onto main~1 main~1"),
    ],
  },
  {
    name: "rebase skips commits that are already upstream and keeps empty ones",
    copiesCommits: true,
    steps: [
      ...base,
      git(P, "switch -c feature"),
      ...commitFile(P, "x.txt", "x\n", "X"),
      ...commitFile(P, "y.txt", "y\n", "Y"),
      git(P, "commit --allow-empty -m Empty"),
      git(P, "switch main"),
      ...commitFile(P, "m.txt", "m\n", "M"),
      git(P, "cherry-pick feature~2"),
      git(P, "switch feature"),
      git(P, "rebase main"),
    ],
  },
  {
    name: "rebase drops a commit whose change is already there",
    copiesCommits: true,
    steps: [
      ...base,
      git(P, "switch -c feature"),
      ...commitFile(P, "a.txt", "1\nX\n3\n", "Same line"),
      ...commitFile(P, "b.txt", "b\n", "Other"),
      git(P, "switch main"),
      ...commitFile(P, "a.txt", "1\nX\n3\n4\n", "Same line and more"),
      git(P, "switch feature"),
      git(P, "rebase main"),
    ],
  },
  {
    name: "rebase refuses to start with uncommitted changes",
    copiesCommits: true,
    steps: [
      ...diverged,
      git(P, "switch feature"),
      write(P, "a.txt", "dirty\n"),
      fails(git(P, "rebase main")),
      git(P, "add a.txt"),
      fails(git(P, "rebase main")),
      write(P, "a.txt", "dirty again\n"),
      fails(git(P, "rebase main")),
      git(P, "reset --hard"),
      write(P, "untracked.txt", "u\n"),
      git(P, "rebase main"),
      fails(git(P, "rebase nope")),
      fails(git(P, "rebase main nope")),
      fails(git(P, "rebase --onto nope main")),
      fails(git(P, "rebase")),
    ],
  },
  {
    name: "rebase a detached HEAD",
    copiesCommits: true,
    steps: [
      ...diverged,
      git(P, "switch --detach feature"),
      ...commitFile(P, "d.txt", "d\n", "D"),
      git(P, "rebase main"),
      git(P, "branch saved"),
    ],
  },
  {
    name: "the reflog brings back the commits a rebase replaced",
    copiesCommits: true,
    steps: [
      ...diverged,
      git(P, "switch feature"),
      git(P, "rebase main"),
      git(P, "branch before-rebase feature@{1}"),
      git(P, "reset --hard HEAD@{4}"),
    ],
  },
  {
    name: "rebase flattens a merge in the branch",
    copiesCommits: true,
    steps: [
      ...diverged,
      git(P, "switch feature"),
      git(P, ["merge", "main", "-m", "Merge main into feature"]),
      ...commitFile(P, "z.txt", "z\n", "Z"),
      git(P, "switch main"),
      ...commitFile(P, "n.txt", "n\n", "N"),
      git(P, "switch feature"),
      git(P, "rebase main"),
    ],
  },
  {
    name: "rebase a merged branch that is already based on main",
    copiesCommits: true,
    steps: [
      ...diverged,
      git(P, "switch feature"),
      git(P, ["merge", "main", "-m", "Merge main into feature"]),
      ...commitFile(P, "z.txt", "z\n", "Z"),
      git(P, "rebase main"),
    ],
  },
  {
    name: "commit during a stopped rebase, then continue",
    copiesCommits: true,
    steps: [
      ...conflicting,
      stops(git(P, "rebase main")),
      write(P, "a.txt", "resolved\n"),
      git(P, "add a.txt"),
      git(P, "commit -m Resolved"),
      git(P, "rebase --continue"),
    ],
  },
  {
    name: "continue without changes drops the stopped commit",
    copiesCommits: true,
    steps: [...conflicting, stops(git(P, "rebase main")), git(P, "checkout HEAD -- a.txt"), git(P, "rebase --continue")],
  },
  {
    name: "reset --hard during a rebase keeps the rebase going",
    copiesCommits: true,
    steps: [
      ...conflicting,
      stops(git(P, "rebase main")),
      git(P, "reset --hard"),
      git(P, "status"),
      git(P, "rebase --abort"),
    ],
  },
  {
    name: "rebase with no argument uses the upstream branch",
    copiesCommits: true,
    steps: [
      ...shared,
      ...commitFile("blaze", "b.txt", "b\n", "Blaze work"),
      git("blaze", "push origin blaze:main"),
      ...commitFile(P, "p.txt", "p\n", "Player work"),
      git(P, "fetch"),
      git(P, "rebase"),
      git(P, "push"),
    ],
  },
  {
    name: "rebase in a robot's worktree, and a branch checked out elsewhere is refused",
    copiesCommits: true,
    steps: [
      ...diverged,
      git(P, "worktree add /crew/drift feature"),
      fails(git(P, "rebase main feature")),
      git("drift", "rebase main"),
      git(P, "log --oneline feature"),
    ],
  },
  {
    name: "pull --rebase replays local commits on top of the remote",
    copiesCommits: true,
    steps: [
      ...shared,
      ...commitFile("blaze", "b.txt", "b\n", "Blaze work"),
      git("blaze", "push origin blaze:main"),
      ...commitFile(P, "p.txt", "p\n", "Player work"),
      git(P, "pull --rebase"),
      git(P, "push"),
      git(P, "pull --rebase"),
      ...commitFile(P, "q.txt", "q\n", "Player again"),
      git(P, "pull --rebase"),
      git("blaze", "pull --rebase origin main"),
    ],
  },
  {
    name: "pull --rebase stops on a conflict and continues",
    copiesCommits: true,
    steps: [
      ...shared,
      ...commitFile("blaze", "a.txt", "1\nblaze\n3\n", "Blaze edit"),
      git("blaze", "push origin blaze:main"),
      ...commitFile(P, "x.txt", "x\n", "Player first"),
      ...commitFile(P, "a.txt", "1\nplayer\n3\n", "Player edit"),
      write(P, "a.txt", "dirty\n"),
      fails(git(P, "pull --rebase")),
      git(P, "checkout -- a.txt"),
      stops(git(P, "pull --rebase")),
      fails(git(P, "pull --rebase")),
      write(P, "a.txt", "1\nboth\n3\n"),
      git(P, "add a.txt"),
      git(P, "rebase --continue"),
      git(P, "push"),
    ],
  },
  {
    name: "pull --rebase after a force push does not bring back dropped commits",
    copiesCommits: true,
    steps: [
      ...shared,
      ...commitFile("blaze", "bad.txt", "oops\n", "Bad commit"),
      git("blaze", "push origin blaze:main"),
      git(P, "pull"),
      ...commitFile(P, "p.txt", "p\n", "Player work"),
      git("blaze", "reset --hard HEAD~1"),
      ...commitFile("blaze", "good.txt", "fine\n", "Good commit"),
      git("blaze", "push -f origin blaze:main"),
      git(P, "pull --rebase"),
    ],
  },
  {
    name: "rebase onto a branch that deleted a file the branch edits",
    copiesCommits: true,
    steps: [
      ...base,
      git(P, "switch -c feature"),
      ...commitFile(P, "a.txt", "1\nF\n3\n", "Edit a"),
      git(P, "switch main"),
      git(P, "rm a.txt"),
      git(P, ["commit", "-m", "Remove a"]),
      git(P, "switch feature"),
      stops(git(P, "rebase main")),
      git(P, "rm a.txt"),
      git(P, "rebase --continue"),
    ],
  },
  {
    name: "rebase stops on two commits in a row",
    copiesCommits: true,
    steps: [
      ...base,
      git(P, "switch -c feature"),
      ...commitFile(P, "a.txt", "1\nF1\n3\n", "F1"),
      ...commitFile(P, "a.txt", "1\nF2\n3\n", "F2"),
      git(P, "switch main"),
      ...commitFile(P, "a.txt", "1\nM\n3\n", "M"),
      git(P, "switch feature"),
      stops(git(P, "rebase main")),
      write(P, "a.txt", "1\nM F1\n3\n"),
      git(P, "add a.txt"),
      stops(git(P, "rebase --continue")),
      git(P, "status"),
      write(P, "a.txt", "1\nM F2\n3\n"),
      git(P, "add a.txt"),
      git(P, "rebase --continue"),
    ],
  },
  {
    name: "rebase with no argument skips commits the upstream dropped in a force push",
    copiesCommits: true,
    steps: [
      ...shared,
      ...commitFile("blaze", "bad.txt", "oops\n", "Bad commit"),
      git("blaze", "push origin blaze:main"),
      git(P, "pull"),
      ...commitFile(P, "p.txt", "p\n", "Player work"),
      git("blaze", "reset --hard HEAD~1"),
      ...commitFile("blaze", "good.txt", "fine\n", "Good commit"),
      git("blaze", "push -f origin blaze:main"),
      git(P, "fetch"),
      git(P, "rebase"),
      git(P, "rebase origin/main"),
    ],
  },
];
