// git stash: saving and restoring work in progress, untracked files, conflicts on apply and pop,
// stash branch, and a stash shared between worktrees.

import { commitFile, del, fails, git, stops, write, type Scenario } from "../scenario";

const P = "player";
const base = [...commitFile(P, "a.txt", "1\n2\n3\n", "Base"), ...commitFile(P, "b.txt", "b\n", "Add b")];

export const stashes: Scenario[] = [
  {
    name: "stash saves changes and pop brings them back",
    steps: [
      ...base,
      git(P, "stash"),
      write(P, "a.txt", "1\nwip\n3\n"),
      write(P, "n.txt", "new\n"),
      git(P, "add n.txt"),
      write(P, "u.txt", "untracked\n"),
      git(P, "stash"),
      git(P, "stash list"),
      git(P, "stash show"),
      git(P, "stash pop"),
      fails(git(P, "stash pop")),
      fails(git(P, "stash drop")),
    ],
  },
  {
    name: "stash -m and -u, list, apply an older entry, drop and clear",
    steps: [
      ...base,
      write(P, "a.txt", "1\nfirst\n3\n"),
      git(P, "stash push -m first"),
      write(P, "b.txt", "second\n"),
      write(P, "u.txt", "untracked\n"),
      git(P, "stash -u -m second"),
      git(P, "stash list"),
      git(P, "stash apply stash@{1}"),
      fails(git(P, "stash apply stash@{5}")),
      git(P, "reset --hard"),
      git(P, "stash apply"),
      git(P, "stash drop stash@{1}"),
      git(P, "stash list"),
      git(P, "stash clear"),
      git(P, "stash list"),
    ],
  },
  {
    name: "stash pop with a conflict keeps the entry",
    steps: [
      ...base,
      write(P, "a.txt", "1\nstashed\n3\n"),
      write(P, "b.txt", "b staged\n"),
      git(P, "add b.txt"),
      git(P, "stash"),
      ...commitFile(P, "a.txt", "1\ncommitted\n3\n", "Change a"),
      stops(git(P, "stash pop")),
      git(P, "stash list"),
      fails(git(P, "stash pop")),
      write(P, "a.txt", "1\nboth\n3\n"),
      git(P, "add a.txt"),
      git(P, "stash drop"),
    ],
  },
  {
    name: "stash apply refuses to overwrite local changes and untracked files",
    steps: [
      ...base,
      write(P, "b.txt", "stashed\n"),
      write(P, "u.txt", "untracked\n"),
      git(P, "stash -u"),
      write(P, "b.txt", "local\n"),
      fails(git(P, "stash apply")),
      git(P, "checkout -- b.txt"),
      write(P, "u.txt", "again\n"),
      fails(git(P, "stash apply")),
      // Real git has already merged b.txt when it finds u.txt in the way; the engine changes nothing.
      git(P, "checkout -- b.txt"),
      del(P, "u.txt"),
      write(P, "z.txt", "z\n"),
      git(P, "add z.txt"),
      git(P, "stash apply"),
    ],
  },
  {
    name: "stash branch starts a branch where the stash was made",
    steps: [
      ...base,
      write(P, "a.txt", "1\nwip\n3\n"),
      write(P, "n.txt", "new\n"),
      git(P, "add n.txt"),
      git(P, "stash"),
      ...commitFile(P, "a.txt", "1\nmoved on\n3\n", "Move on"),
      fails(git(P, "stash branch main")),
      git(P, "stash branch rescue"),
      git(P, "stash list"),
    ],
  },
  {
    name: "stash on a detached HEAD, apply with --index, and stash with nothing to save",
    steps: [
      ...base,
      git(P, "switch --detach HEAD~1"),
      write(P, "a.txt", "1\ndetached\n3\n"),
      git(P, "add a.txt"),
      write(P, "a.txt", "1\ndetached more\n3\n"),
      git(P, "stash"),
      git(P, "stash"),
      git(P, "switch main"),
      git(P, "stash apply --index"),
      git(P, "status"),
    ],
  },
  {
    name: "a robot stashes in its worktree and the player applies it",
    steps: [
      ...base,
      git(P, "worktree add /crew/hoarder"),
      write("hoarder", "b.txt", "hoarded\n"),
      git("hoarder", "stash"),
      git(P, "stash list"),
      git(P, "stash pop"),
      git(P, "commit -am Hoarded"),
    ],
  },
  {
    name: "stash refuses on an unborn branch and during a conflict",
    steps: [
      write(P, "a.txt", "a\n"),
      git(P, "add a.txt"),
      fails(git(P, "stash")),
      git(P, "commit -m Base"),
      git(P, "switch -c side"),
      ...commitFile(P, "a.txt", "side\n", "Side"),
      git(P, "switch main"),
      ...commitFile(P, "a.txt", "main\n", "Main"),
      stops(git(P, "merge side")),
      fails(git(P, "stash")),
    ],
  },
];
